baseURL = 'https://nanjalaantonina.com/'
languageCode = 'en-us'
title = 'Nanjala Antonina'
#theme = 'ananke'
theme = "hugo-split-theme"

[params]
# Section - Visual
[params.visual]

# Image
[params.visual.image]
enable = true
file = "images/bio_image.jpg"
position = "center center"
# Links
#
# Links List #1
[[params.links]]
[params.links.list1]
heading = "Connect"

[[params.links.list1.link]]
text = "Blog"
url = "#"
new_tab = true # new tab

[[params.links.list1.link]]
text = "Email"
url = "#"
new_tab = false # Default, open at same tab

[[params.links.list1.link]]
text = "Newsletter"
url = "#"
